# wordpress/wordpress-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: gcr.io/wordpres123/wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb-service.mariadb.svc.cluster.local
        - name: WORDPRESS_DB_USER
          value: wordpress_user
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress_password
        - name: WORDPRESS_DB_NAME
          value: wordpress_db
        ports:
        - containerPort: 80

---
# wordpress/wordpress-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: wordpress
